name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master  # or the branch you want to deploy from

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Compile src and public folders
      run: |
        mkdir -p compiled
        cp -r src/* compiled/
        cp -r public/* compiled/

    - name: Deploy to different branch
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: page
        publish_dir: ./compiled  # Adjust this to your build output directory
